name: Build Slides for Training and Publish

on:
  pull_request:
    paths:
      - 'slides/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      -
        name: Set up npm for linting
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'
      - 
        name: Lint Markdown
        run: npm ci && npm run mdlint
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Quay.io Container Registry
        uses: docker/login-action@v1 
        with:
          registry: quay.io
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_TOKEN }}
      - 
        name: Build Puzzle Version
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./slides/Dockerfile
          push: true
          tags: |
            quay.io/puzzle/ansible-training-slides:slides-${{ github.event.pull_request.number }}
      -
        name: Run vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'quay.io/puzzle/ansible-training-slides:slides-${{ github.event.pull_request.number }}'
          format: 'table'
          output: 'trivy-results.txt'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os'
          severity: 'CRITICAL,HIGH'
      -
        name: Archive vulnerability scan results
        uses: actions/upload-artifact@v2
        with:
          name: trivy-results-build
          path: trivy-results.txt
      - 
        name: Install Kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: v1.21.2
      - 
        name: Create KUBECONFIG
        env:
          KUBE_CONFIG: '${{ secrets.KUBECONFIG_TEST }}'
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBE_CONFIG"
          echo "$KUBE_CONFIG" > $HOME/.kube/config
      - 
        name: Deploy RevealJS
        env:
          TRAINING_SLIDES_RELEASE: 'slides-${{ github.event.pull_request.number }}'
          TRAINING_NAMESPACE: 'pitc-ansible-training-test'
        run: |
          kubectl rollout restart deployment/$TRAINING_SLIDES_RELEASE-ansible-slides --kubeconfig $HOME/.kube/config --namespace $TRAINING_NAMESPACE
